# -*- coding: utf-8 -*-
"""Assignment 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DdITbn1nhOjMOQuo9APWQh6YMVTa8vq4
"""

li =[int(i) for i in input('Enter values: ').split()]
li.sort()
li.reverse()
print(li)